# Generated by Django 2.2.2 on 2019-06-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
