# Generated by Django 2.2.2 on 2019-06-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_list', '0002_auto_20190628_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=None, max_length=200, unique=True),
        ),
    ]
