# Generated by Django 2.2.2 on 2019-06-29 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_list', '0003_auto_20190628_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='credit',
            new_name='price',
        ),
    ]
